[tox]
envlist = py37, train

[testenv]
deps = -rrequirements.txt
commands = 
    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    pytest -v


[testenv:train]
deps = -rrequirements.txt
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    python src/train_and_evaluate.py --config=params.yaml
    